AllCops:
  TargetRubyVersion: 2.3

Lint/EndAlignment:
  AlignWith: variable

Metrics/LineLength:
  Max: 90

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/IndentArray:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes
